# Generated by Django 5.0.4 on 2024-04-08 08:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('link', models.URLField(verbose_name='Resource link')),
                ('description', models.TextField(verbose_name='Description')),
                ('published_date', models.DateTimeField(verbose_name='Date of publishing')),
                ('media_link', models.URLField(verbose_name='Picture link')),
            ],
        ),
    ]
